[package]
name = "tex2typst"
version = "0.1.4"
edition = "2024"

[lib]
name = "tex2typst"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.0", features = ["extension-module"] }
rquickjs = "0.10.0"
serde_json = "1.0"
